# Generated by Django 5.0.6 on 2024-05-30 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp_car', '0002_personalinfo_delete_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='cedula',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
