# Generated by Django 5.0.6 on 2024-06-11 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('temp_car', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MedicionCompleto',
        ),
    ]
