# Generated by Django 5.0.6 on 2024-06-17 14:50

import django.db.models.deletion
import temp_car.utils.getHours
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp_car', '0003_delete_medicioncompleto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlMonitoreo',
            fields=[
                ('id_Control', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_lectura', models.DateField(default=temp_car.utils.getHours.getDate)),
                ('hora_lectura', models.TimeField(default=temp_car.utils.getHours.getTime)),
                ('id_Lectura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='temp_car.lectura')),
                ('id_User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
