# Generated by Django 3.1.12 on 2025-03-17 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp_car', '0004_controlmonitoreo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
